// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BlogItem: typeof import('./src/components/blog/BlogItem.vue')['default']
    BlogList: typeof import('./src/components/blog/BlogList.vue')['default']
    BlogPasswordDialog: typeof import('./src/components/index/BlogPasswordDialog.vue')['default']
    Comment: typeof import('./src/components/comment/Comment.vue')['default']
    CommentForm: typeof import('./src/components/comment/CommentForm.vue')['default']
    CommentList: typeof import('./src/components/comment/CommentList.vue')['default']
    CommentPagination: typeof import('./src/components/comment/CommentPagination.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Footer: typeof import('./src/components/index/Footer.vue')['default']
    Header: typeof import('./src/components/index/Header.vue')['default']
    Introduction: typeof import('./src/components/sidebar/Introduction.vue')['default']
    MyAPlayer: typeof import('./src/components/index/MyAPlayer.vue')['default']
    Nav: typeof import('./src/components/index/Nav.vue')['default']
    Pagination: typeof import('./src/components/blog/Pagination.vue')['default']
    RandomBlog: typeof import('./src/components/sidebar/RandomBlog.vue')['default']
    Tags: typeof import('./src/components/sidebar/Tags.vue')['default']
    Tocbot: typeof import('./src/components/sidebar/Tocbot.vue')['default']
  }
}

export { }
